### PR TITLE
adding ct and equinix packages to registry

### PR DESCRIPTION
**Pull request by susanev**
second try at https://github.com/pulumi/registry/pull/1274

### CODE REVIEW

**Review by guineveresaenger — CHANGES_REQUESTED** [review]
It looks like both of these providers are missing a [little bit more setup](https://www.pulumi.com/docs/guides/pulumi-packages/how-to-author/)
- specifically a top-level `docs` folder with `_index.md` and `installation_configuration.md` files.

The authors need to provide this documentation, and cut a release tag that includes these changes.

**Comment by susanev** [comment]
@ar4mirez are you able to add the docs in your repos? let me know if i can help in any way!!

**Comment by ar4mirez** [comment]
@susanev thanks for checking, :D I've a little busy with work, but I'll make time to update my PR over the weekend.

**Comment by susanev** [comment]
gonna close this out, pls reopen once you have the time to make the changes. thank you!!

**Pull request closed without merging**
