### PR TITLE
Adding Siderolabs Talos Linux provider

### PR DESCRIPTION
**Pull request by ringods**
The Talos Linux provider from Siderolabs has been transferred ownership to Pulumiverse. I gave it a big refresh and added the initial docs & examples.

## New Provider checklist

- [x] The package's schema URL is correct.
- [x] The package metadata file, if present, contains: 
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [ ] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] Someone from the @pulumi/ai team has reviewed the PR.
- [x] Someone from the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by muhlba91** [comment]
are there any updates on getting this in? :)

**Comment by ringods** [comment]
@AaronFriel I will fix the first two, but the docs explicitly mentions this about the config options:

> There are no provider configuration options. When accessing Talos Linux machines, use the `node` property on the machine related resources.

Source: https://github.com/pulumiverse/pulumi-talos/blob/main/docs/installation-configuration.md?plain=1#L18

**Comment by ringods** [comment]
Fixed in v0.1.5:

https://github.com/pulumiverse/pulumi-talos/blob/v0.1.5/docs/installation-configuration.md

**Review by AaronFriel — APPROVED** [review]
Changes look good to me.

**Review by cnunciato — APPROVED** [review]

**Comment by cnunciato** [comment]
>a front-matter property for the layout set to package.

I'll submit a PR to change these, but they needn't block. (We still handle the "old" versions.)

**Comment by cnunciato** [comment]
https://github.com/pulumiverse/pulumi-talos/pull/63

**Pull request merged**
