### PR TITLE
Add VMware VRealize community package

### PR DESCRIPTION
**Pull request by ringods**
Adding the VMware VRealize (`vra`) provider to the Pulumi Registry.

/cc: @schmidtw

### CODE REVIEW

**Comment by sean1588** [comment]
@ringods - is this ready to be published? I don't see any docs for this provider in the upstream [repo](https://github.com/pulumiverse/pulumi-vra).

**Comment by ringods** [comment]
@sean1588 author is working on it: https://github.com/pulumiverse/pulumi-vra/pull/55

**Comment by iwahbe** [comment]
@ringods Do you still think this PR will land?

**Comment by schmidtw** [comment]
I'm sorry for taking a year and not making any appreciable progress.  My team got the code to work against the internal VRA based service we needed, but that project effectively was canceled shortly afterwards.  I don't have the time to learn the yaml forms of things needed to be able to generate all the docs.

I made the simple changes @ringods asked for in the PR, but at this point, this isn't something I can commit to maintaining or working on.

**Comment by iwahbe** [comment]
No problem @schmidtw. Thanks for taking the time to explain.

**Comment by iwahbe** [comment]
I'm going to close for now. If pulumi-vra finds another maintainer, we'd be happy to look at another PR to add pulumi-vra.

**Pull request closed without merging**
