### PR TITLE
Add Runpod's packages to registry

### PR DESCRIPTION
**Pull request by pierre818181**
## Description

Runpod provides AI/ML infra. This PR aims to merge Runpod's pulumi provider into Pulumi's registry.  

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [ ] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [ ] an example of configuring the provider with environment variables.
- [x] A CODEOWNER has reviewed the PR.
- [x] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Review by cnunciato — CHANGES_REQUESTED** [review]
Thank you @pierre818181! Seeing just a few things we'll need fixed up:

* A few minor formatting and syntactical issues -- I've submitted a PR here to help expedite these: https://github.com/runpod/pulumi-runpod-native/pull/9

* The TypeScript, Go, and YAML languages seem to work as expected (I signed up and grabbed an API key), but when I went to use the Python SDK, I got the following, and wasn't able to figure get past it. Am I doing something wrong?

    ```
    Diagnostics:
      pulumi:pulumi:Stack (python-6b808a7-dev):
        error: Program failed with an unhandled exception:
        Traceback (most recent call last):
          File "/Users/cnunciato/Projects/dev/pulumi/python-6b808a7/__main__.py", line 2, in <module>
            import pulumi_runpod as runpod
        ModuleNotFoundError: No module named 'pulumi_runpod'
    ```

* I also wasn't able to find the C# SDK at all, so I suggest removing the docs on this until you have support for it and it's published in a way that `dotnet add package` works. I've removed the docs in the linked PR to save you some time there as well.

We'll need these changes incorporated and a new version cut before we can merge this PR. Thanks!

**Comment by pierre818181** [comment]
> Thank you @pierre818181! Seeing just a few things we'll need fixed up:
> 
> * A few minor formatting and syntactical issues -- I've submitted a PR here to help expedite these: [Suggestions for overview and install docs runpod/pulumi-runpod-native#9](https://github.com/runpod/pulumi-runpod-native/pull/9)
> * The TypeScript, Go, and YAML languages seem to work as expected (I signed up and grabbed an API key), but when I went to use the Python SDK, I got the following, and wasn't able to figure get past it. Am I doing something wrong?
>   ```
>   Diagnostics:
>     pulumi:pulumi:Stack (python-6b808a7-dev):
>       error: Program failed with an unhandled exception:
>       Traceback (most recent call last):
>         File "/Users/cnunciato/Projects/dev/pulumi/python-6b808a7/__main__.py", line 2, in <module>
>           import pulumi_runpod as runpod
>       ModuleNotFoundError: No module named 'pulumi_runpod'
>   ```
> * I also wasn't able to find the C# SDK at all, so I suggest removing the docs on this until you have support for it and it's published in a way that `dotnet add package` works. I've removed the docs in the linked PR to save you some time there as well.
> 
> We'll need these changes incorporated and a new release cut before we can merge this PR. Thanks!

Thanks @cnunciato. Thanks for the update. 
- I updated it to not publish to dotnet. 
- For Python, you will have to activate the venv for it to work. I found it strange as well but when we run 
```pulumi up```, it uses the Python from the venv and never ends up finding our package. Long run, fix should be on your end I guess.
- We just cut a new release - v1.2.4 and the schema.json references that so I guess we are good on that end.

**Comment by cnunciato** [comment]
>For Python, you will have to activate the venv for it to work. I found it strange as well but when we run
pulumi up, it uses the Python from the venv and never ends up finding our package. Long run, fix should be on your end I guess.

Yeah, I'm definitely in the venv, but still no dice: 

image
 
Do you happen to have a repo that shows a fully working example I could pull down and run? If so, I'd love to see it; I'm just worried your Python users are going to run into the same thing.

I'll go ahead and approve to unblock, though. But if you wouldn't mind putting together that example, I'd appreciate it.

**Review by cnunciato — APPROVED** [review]

**Comment by pierre818181** [comment]
@cnunciato There was something wrong with the pulumi_runpod python package. So I moved it to ```runpodinfra```. If possible, please test it. I tested all the SDKs once more and they looked fine. 

I rebased the main branch and was not able to merge it. Can you run the workflow once more?

**Pull request merged**
