### PR TITLE
Revert "Revert "feat: add rediscloud""

### PR DESCRIPTION
**Pull request by susanev**
Reverts pulumi/registry#2488

@rawkode this failed our build in docs
build-failure

i think ur gonna have to put the URLs in quotes

### CODE REVIEW

**Comment by susanev** [comment]
ill try and update for ya

**Comment by rawkode** [comment]
@susanev Can you change version to 1.2.5, please?

I think the build metadata is causing problems

**Comment by rawkode** [comment]
That seems more promising :)

**Comment by rawkode** [comment]
@susanev let me know if there's anything else you need me to do.

Thanks for your help

**Comment by susanev** [comment]
@rawkode i need to move this over to the community packages, but i can handle it. will let ya know if i need anything else from ya.

**Pull request merged**
