### PR TITLE
Adjust some styles for registry nav and browse

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
Addressing a handful of papercuts:

### browse page
- [ ] change card headers from `font-weight: 700;` to `font-weight: 600;`
- [ ] adjust max-height of the empty package placeholder 
Screen Shot 2022-12-05 at 2 40 09 PM

- [ ] leave empty space underneath filters so content doesn't jump down when chips appear; should be about 50px of space needed
Screen Shot 2022-12-05 at 2 40 28 PM

### package navigation
- [x] change text-color for inactive menu navigation tabs to align with inactive language selectors `#5f6065`
Screen Shot 2022-12-05 at 2 46 41 PM

### other
- [x] add alt text to all logos: `"<package name> logo"`

Screen Shot 2022-12-05 at 2 43 29 PM

### CODE REVIEW

**Comment by susanev** [comment]
@kimberleyamackenzie is it possible to minimize the amount of space between the space for the chips and the a-z headings? i think there's a lot of extra margin or padding in there that we could get rid of

**Comment by kimberleyamackenzie** [comment]
@susanev right now the A-Z h2 has 32px top margin, this is what it looks like w/ chips if we take that away entirely.  thoughts on what the right value is?  
Screen Shot 2022-12-05 at 3 14 28 PM

**Comment by susanev** [comment]
@kimberleyamackenzie this looks great, so lets remove it or set it 0

**Comment by kimberleyamackenzie** [comment]
Done in the latest commit.

**Review by anita-trimbur — APPROVED** [review]

**Pull request merged**
