### PR TITLE
add datarobot community provider

### PR DESCRIPTION
**Pull request by NolanJMcCafferty**
## Description

Add DataRobot provider

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL in this PR is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a valid plugin download URL. See [Publish Your Package](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#publish-your-package).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [ ] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] The repository has:
  - [x] a version tag prefixed with `v` that corresponds with a valid GitHub release and published package SDKs
- [ ] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by jkodroff** [comment]
@NolanJMcCafferty A couple issues I've noted:

1. There's no .NET SDK: https://github.com/datarobot-community/pulumi-datarobot/blob/main/docs/installation-configuration.md
2. The link to the Go SDK (from the installation and configuration page linked above) is broken (not sure if this is expected or not): https://pkg.go.dev/github.com/datarobot-community/pulumi-datarobot/sdk
3. You should add links to SDKs here (but it's not the most common path for Pulumi users to install provider SDKs): https://github.com/datarobot-community/pulumi-datarobot/blob/main/README.md
4. The TS example has YAML as its language: https://github.com/datarobot-community/pulumi-datarobot/blob/main/docs/_index.md

**Comment by NolanJMcCafferty** [comment]
Posted this here along with the email sent to Josh:

We are currently running into this error when trying to publish the .NET SDK as Pulumi.Datarobot: 

`error: Response status code does not indicate success: 409 (This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID. Go to https://docs.microsoft.com/nuget/reference/id-prefix-reservation learn more about Package ID prefix reservation.).`

Do you know why "Pulumi.Datarobot" would already be reserved? I don't see any packages on Nuget with that identifier. Could it be because we don't have permissions to publish to "Pulumi." ?

**Review by ringods — CHANGES_REQUESTED** [review]
@NolanJMcCafferty there seems to be some mismatch to the `chooser`/`choosable` tags in `docs/_index.md`. Like HTML, the closing tags should match the opening tags.

For instance, these closing tags do not match up with any opening tag:

https://github.com/datarobot-community/pulumi-datarobot/blob/ca42570c79ff0667343f4a07918956a3c37441ae/docs/_index.md#L13-L15

Can you fix this and create a new release containing this fix?

**Comment by NolanJMcCafferty** [comment]
@ringods Ok I have updated the `_index.md` file and released the fix.

**Review by ringods — APPROVED** [review]

**Comment by cnunciato** [comment]
cc @pulumi/docs @sean1588 for a review & merge as I'm currently out.

**Review by sean1588 — APPROVED** [review]
thanks @NolanJMcCafferty! Looks good to me.

**Pull request merged**
