### PR TITLE
feat: add kuraudo-io/pulumi-symbiosis

### PR DESCRIPTION
**Pull request by hbjydev**
This PR is to hopefully get the kuraudo-io/pulumi-symbiosis Terraform bridge provider published.

I know there's stuff missing from this, so any input on what I'm missing is appreciated. :)

### CODE REVIEW

**Comment by susanev** [comment]
ive added a logo for when this lands
https://github.com/pulumi/pulumi-hugo/pull/2267

**Comment by hbjydev** [comment]
@susanev Thanks! :D

**Comment by ringods** [comment]
Hello @hbjydev To have your components published on the Pulumi Registry, you still have to do 2 things in this order:

1. add a docs folder in your repo here containing two files. These files provide the content for the `Overview` and `Installation & Configuration` tabs for your listing in the Pulumi Registry. See the [Unifi example](https://github.com/pulumiverse/pulumi-unifi/tree/main/docs).
   * `_index.md`: general description of your package.
   * `installation-configuration.md`: any documentation on the providers you use for your components.
1. create a new release of your components. The Git tag should point to a revision containing the docs folder

Please notify us here when this is done and we will merge this PR.

**Comment by hbjydev** [comment]
@ringods That's all done now, so it should be sorted. I made the tag v0.1.5 and sdk/v0.1.5 as per the docs :)
All packages are published

**Review by ringods — APPROVED** [review]

**Pull request merged**
