### PR TITLE
add wttech/pulumi-aem

### PR DESCRIPTION
**Pull request by dominik-przybyl-wttech**
## Description

Add wttech/pulumi-aem to Pulumi Registry.

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL is correct.
- [ ] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Review by ringods — CHANGES_REQUESTED** [review]
@dominik-przybyl-wttech still a few findings needing a fix in your repo:

* the category should be `category/cloud` instead of `cloud` ([here](https://github.com/pulumi/registry/pull/4605))
* can you expand the acronym `AEM` to `Adobe Experience Manager` in the `description` field? ([here](https://github.com/wttech/pulumi-aem/blob/main/provider/cmd/pulumi-resource-aem/schema.json#L4))
* can you add a `displayName` property to the schema reading `Adobe Experience Manager`? ([example](https://github.com/pulumiverse/pulumi-unifi/blob/main/provider/cmd/pulumi-resource-unifi/schema.json#L3))
* Fix the link to the Go SDK docs on pkg.go.dev ([here](https://github.com/wttech/pulumi-aem/blob/main/docs/installation-configuration.md?plain=1#L13C51-L13C102))
* Add the following to `docs/installation-configuration.md`:
  * a copyable command for installing the resource plugin if necessary.
  * an example of configuring the provider with pulumi config set.
  * an example of configuring the provider with environment variables.
For the last 3 bullet points, here is an [example from the Scaleway provider](https://github.com/pulumiverse/pulumi-scaleway/blob/main/docs/installation-configuration.md).

These fixes need to end up in a new release of your package.

**Review by krystian-panek-wttech — APPROVED** [review]

**Comment by ringods** [comment]
@krystian-panek-wttech @dominik-przybyl-wttech there are still a few issues from the list I reported earlier which are not resolved. Can you go over these please?

After fixing these, you have to make a release containing these fixes before we can can merge this PR.

**Comment by dominik-przybyl-wttech** [comment]
A new release is available: https://github.com/wttech/pulumi-aem/releases/tag/v0.1.2. I've fixed all mentioned issues.
Regarding the Go SDK on [pkg.go.dev](http://pkg.go.dev/), it is available: https://proxy.golang.org/github.com/wttech/pulumi-aem/sdk/@v/v0.1.2.info. However, it is not yet visible on [pkg.go.dev](http://pkg.go.dev/). I am still working to resolve this.
Is this a blocker, or can we proceed with adding the AEM provider to the Pulumi repository?

**Comment by ringods** [comment]
@cnunciato would you have an idea why the Go documentation doesn't show up `pkg.go.dev`?

**Comment by dominik-przybyl-wttech** [comment]
@ringods, Go documentation is now available on https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk

**Comment by dominik-przybyl-wttech** [comment]
@ringods, @cnunciato, @sean1588 Go documentation is now available on https://pkg.go.dev/github.com/wttech/pulumi-aem/sdk, can you continue the review?

**Comment by ringods** [comment]
@dominik-przybyl-wttech will have a look today, but can you rebase your branch against `master` rather than merging `master` into your branch?

**Comment by dominik-przybyl-wttech** [comment]
done

**Comment by dominik-przybyl-wttech** [comment]
@ringods, @cnunciato, @sean1588 is everything fine with this PR now, or is any additional work required?

**Review by ringods — APPROVED** [review]
Looks good to me. I'll ping one of my colleagues for a second pair of eyes.

**Comment by dominik-przybyl-wttech** [comment]
Thank you @ringods , good news

**Review by sean1588 — APPROVED** [review]
Thanks @dominik-przybyl-wttech ! I'm going to get this merged and should be live today. Sorry about the wait here!!

**Pull request merged**
