### PR TITLE
added influxdb3 provider

### PR DESCRIPTION
**Pull request by thulasirajkomminar**
added influxdb3 provider

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL in this PR is correct.
- [x] The package metadata file, if present, contains:
  - [ ] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [ ] a valid plugin download URL. See [Publish Your Package](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#publish-your-package).
  - [ ] a description that explains what the package does.
  - [ ] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [ ] a brief explanation of what the package is and what it does.
  - [ ] at least one representative example in all supported languages.
  - [ ] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [ ] links to SDKs in all supported languages.
  - [ ] a copyable command for installing the resource plugin if necessary.
  - [ ] an example of configuring the provider with `pulumi config set`.
  - [ ] an example of configuring the provider with environment variables.
- [x] The repository has:
  - [ ] a version tag prefixed with `v` that corresponds with a valid GitHub release and published package SDKs
- [ ] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by sean1588** [comment]
Hi @thulasirajkomminar thanks for opening this PR to contribute another provider. I have a couple of questions for you. I notice that you are publishing influxdb3 as a new provider. We already do have an influxdb provider hosted in the registry that looks like it was also contributed by you. Is this just a v3 version of the influxdb provider? We currently do not support hosting multiple versions of providers in the registry (but do have plans to enable this in the future) and only host docs for the latest one. Publishing it this way will result in two separate provider listings of different versions and something we do not encourage as to not cause confusion to our users. Can we just publish this as a new latest version of the current influxdb provider?

**Comment by thulasirajkomminar** [comment]
> Hi @thulasirajkomminar thanks for opening this PR to contribute another provider. I have a couple of questions for you. I notice that you are publishing influxdb3 as a new provider. We already do have an influxdb provider hosted in the registry that looks like it was also contributed by you. Is this just a v3 version of the influxdb provider? We currently do not support hosting multiple versions of providers in the registry (but do have plans to enable this in the future) and only host docs for the latest one. Publishing it this way will result in two separate provider listings of different versions and something we do not encourage as to not cause confusion to our users. Can we just publish this as a new latest version of the current influxdb provider?

Hey @sean1588 Thanks for reviewing my PR. Yes both providers are for same InfluxDB, but V2 & V3 are completely different with lot changed in the APIs and how the resources are called are very different in both versions. Both versions have different DB flavours and maintaining it in the same repo will be extremely complex. So thats why I have created separate providers in Terraform to develop & maintain both at the same time. Hope this answers your question.

**Comment by sean1588** [comment]
thanks for the clarification @thulasirajkomminar! While we typically try to not encourage doing this, I think it makes sense to make an exception in this case for the reasons you outlined, given the APIs are so different.

**Comment by sean1588** [comment]
@thulasirajkomminar - once this PR gets merged through, the registry will start to pull the docs from your repo, `komminarlabs/pulumi-influxdb3`. I was taking a quick glance at the overview and installation and config pages. I noticed you have the language chooser specifying four languages, ts, python, go and csharp. Looks like the csharp example is either missing or you just included it in the listing accidentally. Can you either remove csharp or add a code example for that?

https://github.com/komminarlabs/pulumi-influxdb3/blob/main/docs/_index.md?plain=1#L13

**Comment by thulasirajkomminar** [comment]
> @thulasirajkomminar - once this PR gets merged through, the registry will start to pull the docs from your repo, `komminarlabs/pulumi-influxdb3`. I was taking a quick glance at the overview and installation and config pages. I noticed you have the language chooser specifying four languages, ts, python, go and csharp. Looks like the csharp example is either missing or you just included it in the listing accidentally. Can you either remove csharp or add a code example for that?
> 
> https://github.com/komminarlabs/pulumi-influxdb3/blob/main/docs/_index.md?plain=1#L13

@sean1588 Fixed it and released a new version https://github.com/komminarlabs/pulumi-influxdb3/releases/tag/v1.0.1

**Review by sean1588 — APPROVED** [review]

**Comment by sean1588** [comment]
thank you @thulasirajkomminar !

**Pull request merged**
