### PR TITLE
Add Tencent Cloud Provider to package list

### PR DESCRIPTION
**Pull request by Kagashino**
The Tencent Cloud provider maintained by TencentCloudStak and can be used to provision most of the cloud resources available in [Tencent Cloud](https://tencentcloud.com).
The provider was bridged from [pulumi-tf-provider-boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate) and already done with basic document, release workflow and examples.

### CODE REVIEW

**Comment by ringods** [comment]
Hello @Kagashino, we want to contact you regarding this provider. Can you reach out to us via this form?

https://www.pulumi.com/contact/?form=registry

Preferrably add a link to this PR.

**Comment by Kagashino** [comment]
> Hello @Kagashino, we want to contact you regarding this provider. Can you reach out to us via this form?
> 
> https://www.pulumi.com/contact/?form=registry
> 
> Preferrably add a link to this PR.

Hi, an email has been sent in the name of TencentCloud Infrastructure as Code Team, by filling the form of the contact page.

**Comment by susanev** [comment]
@Kagashino have yall been able to get our emails?

**Comment by susanev** [comment]
closing this out because we haven't been able to connect with yall. pls reopen if yall have the time for a quick convo. thank you!!

**Pull request closed without merging**
