### PR TITLE
Add Splight Provider

### PR DESCRIPTION
**Pull request by smartinellimarco**
## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release. 
  - **:warning: I set the version with Goreleaser but could not find it in the generated `schema.json`**
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Review by ringods — CHANGES_REQUESTED** [review]
Hello @smartinellimarco,

No problem having no version in the schema file. We should update this template to reflect that.

There are some other things that still require changes:

* Your `provider/resources.go` doesn't have the `PluginDownloadURL` property set. You can find more info regarding the value in [Author packages in Pulumi Registry](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#support-for-github-releases). Regenerate all SDKs after setting this value.
* The copyable command to install the plugin binary. See an [example from the Grafana provider](https://github.com/pulumiverse/pulumi-grafana/blob/5aac7f00d6354197352fe833f354982add751ea7/docs/installation-configuration.md#L16-L24), which also includes the `--server` argument including the same plugin download URL value.
* Configuring the token should use Pulumi's secrets support: `pulumi config set splight:token --secret <Enter>` (do not paste the value on the shell as it ends up in your shell history)

**Comment by smartinellimarco** [comment]
I have implemented the changes in this pull request. Could you please review to ensure they are correct?

[Link to pull request](https://github.com/splightplatform/pulumi-splight/pull/13/files)

Thank you!

**Comment by smartinellimarco** [comment]
Hi @ringods,

The requested changes have been included in the latest release, along with several other fixes.

Best regards

**Review by ringods — APPROVED** [review]

**Review by sean1588 — APPROVED** [review]

**Comment by marianogaragiola** [comment]
Does anyone know when this provider will be available for use?

**Comment by ringods** [comment]
@marianogaragiola the provider was already usable. Our Registry only publishes the docs. We don't host the provider itself.

**Pull request merged**
