### PR TITLE
added a-schot/pulumi-dbtcloud to community package list

### PR DESCRIPTION
**Pull request by a-schot**
## Description

Added a bridged provider for dbt Cloud. 

- The logo which can be used for the Pulumi Registry can be found [here](https://drive.usercontent.google.com/download?id=161Q-cnyIorAonWrV_YcvRpJBWAt44q0g&authuser=0), couldn't find where to submit this, however.
- Any tips on how to exclude the legacy `dbt_cloud`-prefixed resources would be much appreciated. I had to map them all to `Legacy<resourcename>`, otherwise the binary would panic.

## Adding a new package?

If this pull request adds a new package:

- [X] The package's schema URL is correct.
- [X] The package metadata file, if present, contains: 
  - [X] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [X] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [X] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [X] a brief explanation of what the package is and what it does.
  - [X] at least one representative example in all supported languages.
  - [X] a front-matter property for the `layout` set to `package`.
- [X] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [X] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [X] an example of configuring the provider with `pulumi config set`.
  - [X] an example of configuring the provider with environment variables.
- [ ] A CODEOWNER has reviewed the PR.
- [ ] Someone from the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by ringods** [comment]
@a-schot Please integrate the following changes in your provider repository:

### Logo

Commit the icon to your repo, and set the `LogoURL` in `provider/resource.go` like this:

https://github.com/ctfer-io/pulumi-ctfd/blob/main/provider/resources.go#L35

### Plugin Download URL

Preferrably use the [explicit support for Github Releases](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#support-for-github-releases) as the `PluginDownloadURL`. Example:

https://github.com/ctfer-io/pulumi-ctfd/blob/main/provider/resources.go#L32

### Command to download the plugin

Please add a section to `docs/installation-configuration.md` documenting how to download the plugin binary. Use the special Github URL from previous section as the value for the `--server` argument. Example:

https://github.com/ctfer-io/pulumi-ctfd/blob/main/docs/installation-configuration.md?plain=1#L16-L24

### Legacy resources

In the meantime, I will check with our engineering team how to hide the legacy resources/datasources.

**Review by ringods — CHANGES_REQUESTED** [review]
@a-schot Please integrate the following changes in your provider repository:

### Logo

Commit the icon to your repo, and set the `LogoURL` in `provider/resource.go` like this:

https://github.com/ctfer-io/pulumi-ctfd/blob/main/provider/resources.go#L35

### Plugin Download URL

Preferrably use the [explicit support for Github Releases](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#support-for-github-releases) as the `PluginDownloadURL`. Example:

https://github.com/ctfer-io/pulumi-ctfd/blob/main/provider/resources.go#L32

### Command to download the plugin

Please add a section to `docs/installation-configuration.md` documenting how to download the plugin binary. Use the special Github URL from previous section as the value for the `--server` argument. Example:

https://github.com/ctfer-io/pulumi-ctfd/blob/main/docs/installation-configuration.md?plain=1#L16-L24

### Legacy resources

In the meantime, I will check with our engineering team how to hide the legacy resources/datasources.

**Comment by a-schot** [comment]
@ringods Thanks for the feedback! 

I implemented the three points mentioned in your reply and ticked the boxes in the original PR text to reflect that.

**Comment by ringods** [comment]
@a-schot I noticed an incorrect value for your download URL.

https://github.com/a-schot/pulumi-dbtcloud/commit/2330d98bc0e5f7ece439080d75c0910ed50c99d5#r140550943

After fixing the download URL, can you create a new release of your package containing all these changes?

**Comment by a-schot** [comment]
@ringods Good catch.

I fixed it and released a new version: https://github.com/a-schot/pulumi-dbtcloud/actions/runs/8540656535

**Comment by ringods** [comment]
@a-schot to ignore some of the legacy TF resources and not expose these in the Pulumi version, you should be able to use the `IgnoreMappings` property within `provider/resources.go`:

https://github.com/pulumi/pulumi-terraform-bridge/blob/9257734f4e75379fc05f0d99dd19b461111b44b1/pkg/tfbridge/info.go#L86

**Comment by a-schot** [comment]
@ringods It doesn't seem like that is happening right now. I am using that property currently for all `dbt_cloud_` prefixed resources/datasources. This does prevent the errors thrown by `tfgen` but the binary will still panic at runtime (see pulumi/pulumi-terraform-bridge/issues/1838)

**Comment by ringods** [comment]
@a-schot checking in again as we haven't heard from you in a few weeks. Would you have time to checkout v3.80.0 of our bridge which contains the fix to ignore some mappings?

**Pull request closed without merging**
