### PR TITLE
Add pulumi-influxdb community package

### PR DESCRIPTION
**Pull request by thulasirajkomminar**
Add pulumi-influxdb community package

## Description

[InfluxDB](https://www.influxdata.com/) community package.

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL is correct.
- [x] The package metadata file, if present, contains: 
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] A CODEOWNER has reviewed the PR.
- [x] Someone from the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Review by ringods — CHANGES_REQUESTED** [review]
@thulasirajkomminar  In files `docs/_index.md` and `docs/installation-configuration.md`, the front-matter property for the `layout` must be set to `package`:

```
---
...
layout: package
---
```

**Comment by thulasirajkomminar** [comment]
> @thulasirajkomminar In files `docs/_index.md` and `docs/installation-configuration.md`, the front-matter property for the `layout` must be set to `package`:
> 
> ```
> ---
> ...
> layout: package
> ---
> ```

@ringods Do you have an example/sample for this?

**Comment by thulasirajkomminar** [comment]
> @thulasirajkomminar see the docs here:
> 
> https://github.com/pulumiverse/pulumi-scaleway/tree/main/docs
> 
> You should set the markdown files in the `docs` folder of your Pulumi provider similary _and_ include these in a release.

@ringods Thanks.. Released a new version with the docs update.

**Comment by ringods** [comment]
@thulasirajkomminar thanks for fixing this.

There is another thing to fix though. In `docs/installation-configuration.md`, the command to install your plugin is not correct. You have this:

```bash
pulumi plugin install resource InfluxDB <version>
```

While it should be:

```bash
pulumi plugin install resource influxdb <version> --server github://api.github.com/komminarlabs
```

I also made the name of the plugin fully lowercase.

I will approve this PR for now, but can you update this for a next release of your provider?

**Review by ringods — APPROVED** [review]

**Comment by thulasirajkomminar** [comment]
> @thulasirajkomminar thanks for fixing this.
> 
> There is another thing to fix though. In `docs/installation-configuration.md`, the command to install your plugin is not correct. You have this:
> 
> ```shell
> pulumi plugin install resource InfluxDB <version>
> ```
> 
> While it should be:
> 
> ```shell
> pulumi plugin install resource influxdb <version> --server github://api.github.com/komminarlabs
> ```
> 
> I also made the name of the plugin fully lowercase.
> 
> I will approve this PR for now, but can you update this for a next release of your provider?

@ringods Thanks for the approval. I will add your suggestions to my next release

**Review by cnunciato — APPROVED** [review]

**Pull request merged**
