### PR TITLE
Add crowdstrike community package

### PR DESCRIPTION
**Pull request by gtheodorio**
add crowdstrike repo to package list

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL in this PR is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a valid plugin download URL. See [Publish Your Package](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#publish-your-package).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x ] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [ ] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] The repository has:
  - [x] a version tag prefixed with `v` that corresponds with a valid GitHub release and published package SDKs
- [ ] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by mjeffryes** [comment]
Thanks for the contribution @gtheodorio! And I apologize that no one replied on this PR right away.

We'd be happy to add this provider in the registry, but we do have a policy that new providers should have SDKs published in all Pulumi languages and that the examples on the docs pages support all Pulumi languages as well. It looks like this package is published everywhere except in Nuget for dotnet users; would you be willing to publish those and link to them in your docs and then we can get this in.

**Comment by gtheodorio** [comment]
@mjeffryes Thanks for the update. I'll go ahead and create an SDK for dotnet.

**Comment by gtheodorio** [comment]
@mjeffryes The dotnet package has been added. https://www.nuget.org/packages/CrowdStrike.Crowdstrike

**Review by guineveresaenger — APPROVED** [review]
non-blocking: please add dotnet example to index.md page.

**Comment by guineveresaenger** [comment]
Also - @gtheodorio thank you so much for adding the NuGet package! 

Cheers and thank you for adding to the ecosystem! 🎉

**Pull request merged**
