### PR TITLE
Update Twingate provider

### PR DESCRIPTION
**Pull request by twingate-blee**
## Description

We are updating the repo of our Pulumi provider 

Rrom: 
https://github.com/Twingate-Labs/pulumi-twingate

To:
https://github.com/Twingate/pulumi-twingate

There is a new version and documentation in the new repo

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by ringods** [comment]
@twingate-blee I'm quite surprised to see these are 2 distinct repositories. Is this intentional? I'm explicitely verifying because this will be a breaking upgrade for users of the old Labs provider to go to the new provider. I compared the Pulumi `schema.json` file from both providers and there are substantial differences between them in:

* resource type identifiers not matching
* properties in the old provider no longer existing in the new provider
* properties going from arrays to singular type
* propeties going from singular type to arrays

**Comment by twingate-blee** [comment]
@ringods Yes this is intentional. We want to move away from the twingate-labs/pulumi-twingate repo to the twingate/pulumi-twingate repo.
The provider in labs is built from version 1.2.1 of our twingate terraform provider. The new repo is built from 3.0.0 there has been many updates and breaking changes between the two major versions so that will account for the substantial differences.

For current users of the pulumi provider if they referenced the labs npm ie https://www.npmjs.com/package/@twingate-labs/pulumi-twingate/v/0.0.48 shouldn't everything still work for them? They can then decided to upgraded with breaking changes to the new provider at https://www.npmjs.com/package/@twingate/pulumi-twingate/v/3.0.0

**Comment by twingate-blee** [comment]
Yes we are aware and fine with that.

**Review by ringods — CHANGES_REQUESTED** [review]
@twingate-blee here are still some things needing an update:

* Commit a PNG logo (no SVG) to the repository and set the `LogoURL` in `provider/resources.go`
* Please use a custom `RootNamespace` for the dotnet SDK referring to Twingate. See how Pulumiverse community documented [where to add this property](https://github.com/pulumiverse/infra/blob/main/README.md#nuget) in `resources.go`. After changing this value, regenerate schema and the SDK and commit the changed files.
* In `docs/_index.md`, add example for Go and dotnet too.
* In `docs/installation-configuration.md`:
  * update the dotnet package name to reflect the chosen `RootNamespace`. It currently still points to the labs package.
  * update the link to the README at the end of the file. It currently still points to the labs repository. Update the branch name too from `master` (in Labs) to `main` (in the new repo)

After applying all these changes, please make a new release including all of these.

**Comment by twingate-blee** [comment]
@ringods Here is a PR https://github.com/Twingate/pulumi-twingate/pull/44 with the requested changes. Let me know if this looks good and I can merge it. Thanks

**Comment by twingate-blee** [comment]
@ringods we pushed out [v3.0.1](https://github.com/Twingate/pulumi-twingate/releases/tag/v3.0.1) with the requested changes

**Review by ringods — APPROVED** [review]

**Review by sean1588 — APPROVED** [review]

**Pull request merged**
