### PR TITLE
Update package-list.json

### PR DESCRIPTION
**Pull request by littlejo**
Add https://github.com/littlejo/pulumi-cilium

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL is correct.
- [x] The package metadata file, if present, contains: 
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [ ] an example of configuring the provider with environment variables.
- [ ] Someone from the @pulumi/ai team has reviewed the PR.
- [x] Someone from the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by ringods** [comment]
@littlejo you can't use the `pulumiverse` NPM scope or .NET namespace since your provider is not in the `https://github.com/pulumiverse` organization.

You should choose your own namespaces.

**Comment by littlejo** [comment]
@ringods it should be good now.

**Comment by ringods** [comment]
@littlejo still one to go unfortunately:

https://github.com/littlejo/pulumi-cilium/blob/3a31c62d465897ddd9a4f5bbbd9d7b69d9df6d88/provider/resources.go#L179

**Comment by littlejo** [comment]
@ringods i don't use C# for pulumi for the moment. Is it really important for the registry?

**Comment by littlejo** [comment]
@ringods it should be good now.

**Review by cnunciato — CHANGES_REQUESTED** [review]
Almost there! We need a few final things fixed up first -- PR here that should do it: https://github.com/littlejo/pulumi-cilium/pull/31 (And then we'll need you to cut a new GitHub release containing these changes.)

I unchecked a couple of boxes as well (around configuring the provider). We should add those docs as well if we can. The Aiven provider is a good example to work by: https://www.pulumi.com/registry/packages/aiven/installation-configuration

Thanks for taking the time to do this!

**Comment by littlejo** [comment]
> I unchecked a couple of boxes as well (around configuring the provider). We should add those docs as well if we can. The Aiven provider is a good example to work by: https://www.pulumi.com/registry/packages/aiven/installation-configuration

There is no environment variable for the moment.

**Comment by littlejo** [comment]
What is the blocker of this PR?

**Review by cnunciato — APPROVED** [review]
Looks like this is good to go. Thanks @littlejo!

**Pull request merged**
