### PR TITLE
Add pulumi-cratedb community package

### PR DESCRIPTION
**Pull request by thulasirajkomminar**
## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL in this PR is correct.
- [ ] The package metadata file, if present, contains:
  - [ ] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [ ] a valid plugin download URL. See [Publish Your Package](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#publish-your-package).
  - [ ] a description that explains what the package does.
  - [ ] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] The repository has:
  - [x] a version tag prefixed with `v` that corresponds with a valid GitHub release and published package SDKs
- [x] A CODEOWNER has reviewed the PR.
- [x] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by sean1588** [comment]
Thanks @thulasirajkomminar for this contribution and the others you have made as well!

Couple of small things:

- We should have an example in each of the languages that are supported. Looks like we are missing a .NET one.
- It may also be worth updating the displayName in the schema to be `CrateDB` if that is how it is. https://github.com/komminarlabs/pulumi-cratedb/blob/main/provider/cmd/pulumi-resource-cratedb/schema.json#L3C5-L3C30

**Comment by thulasirajkomminar** [comment]
> Thanks @thulasirajkomminar for this contribution and the others you have made as well!
> 
> Couple of small things:
> 
> * We should have an example in each of the languages that are supported. Looks like we are missing a .NET one.
> * It may also be worth updating the displayName in the schema to be `CrateDB` if that is how it is. https://github.com/komminarlabs/pulumi-cratedb/blob/main/provider/cmd/pulumi-resource-cratedb/schema.json#L3C5-L3C30

@sean1588 Release a new [version](https://github.com/komminarlabs/pulumi-cratedb/releases/tag/v0.2.0)

**Comment by sean1588** [comment]
@thulasirajkomminar - thanks for the quick turnaround!

One more thing though. Thanks for adding csharp, but one last thing is you need to add csharp to the top level chooser element in order for it to render in the code chooser.

https://github.com/komminarlabs/pulumi-cratedb/blob/main/docs/_index.md?plain=1#L13

Should be:

```
{{< chooser language "typescript,python,go,csharp" >}}
```

**Comment by thulasirajkomminar** [comment]
> @thulasirajkomminar - thanks for the quick turnaround!
> 
> One more thing though. Thanks for adding csharp, but one last thing is you need to add csharp to the top level chooser element in order for it to render in the code chooser.
> 
> https://github.com/komminarlabs/pulumi-cratedb/blob/main/docs/_index.md?plain=1#L13
> 
> Should be:
> 
> ```
> {{< chooser language "typescript,python,go,csharp" >}}
> ```

@sean1588 Sorry about that missed it. Created a new [release](https://github.com/komminarlabs/pulumi-cratedb/releases/tag/v0.2.1)

**Review by sean1588 — APPROVED** [review]
Thanks @thulasirajkomminar ! LGTM

**Pull request merged**
