### PR TITLE
feat: add pulumi-vercel to registry

### PR DESCRIPTION
**Pull request by omercnet**

### CODE REVIEW

**Comment by AaronFriel** [comment]
Hey @omercnet, thanks for contributing a provider! I think the docs build will fail as we will need your repository to have a couple additional files in the `docs` directory, here's another example of a Pulumiverse repository as an example:

https://github.com/pulumiverse/pulumi-harbor/tree/main/docs

**Review by AaronFriel — CHANGES_REQUESTED** [review]
Need `docs/_index.md` and `docs/installation-configuration.md` files for documentation.

**Comment by omercnet** [comment]
> Need `docs/_index.md` and `docs/installation-configuration.md` files for documentation.

is this something generated by the bridge provider or do I need to maintain it manually?

**Comment by ringods** [comment]
@omercnet this is a manual thing. Here is an example:

https://github.com/pulumiverse/pulumi-exoscale/tree/main/docs

After adding these files, please make a new release which includes the `docs` folder in the git tag.

**Comment by omercnet** [comment]
https://github.com/pulumiverse/pulumi-vercel/pull/41

**Comment by omercnet** [comment]
@AaronFriel v0.15.1 has been released with the doc fix

**Review by AaronFriel — APPROVED** [review]

**Comment by AaronFriel** [comment]
@omercnet thank you for the update and contribution!

You may want to take a look at the [installation config](https://github.com/pulumiverse/pulumi-vercel/blob/main/docs/installation-configuration.md) as it looks like the Go SDK should not have "/v3" at the end. Go SDKs won't include a major version number until you release major version 2.

**Pull request merged**
