### PR TITLE
Add pulumi-cpln community package

### PR DESCRIPTION
**Pull request by vavsab**
## Description

Please add a new pulumiverse/pulumi-cpln package to the registry.

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL is correct.
- [x] The package metadata file, if present, contains: 
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] A CODEOWNER has reviewed the PR.
- [x] Someone from the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by vavsab** [comment]
@susanev @stack72 @ringods could you please take a look at this PR?

**Comment by ringods** [comment]
@vavsab this is up to the reviewers assigned to this PR. 

FYI `susanev` and `stack72` don't work for Pulumi anymore.

**Comment by vavsab** [comment]
@sean1588 @cnunciato @AaronFriel Could you please take a look at this PR?

**Comment by vavsab** [comment]
@sean1588 @cnunciato @AaronFriel Could anyone look at this PR?

**Review by ringods — CHANGES_REQUESTED** [review]
@vavsab In files `docs/_index.md` and `docs/installation-configuration.md`, the front-matter property for the `layout` must be set to `package`:

```
---
...
layout: package
---
```

**Comment by cnunciato** [comment]
@vavsab In your install/configuration doc, you link to the Terraform Registry. Can you instead pull those docs into your Pulumi provider repo, so users don't have to leave the Pulumi Registry?

**Comment by vavsab** [comment]
@cnunciato thank you for your contribution. Merged your changes. Will fix the auth docs tomorrow

**Comment by vavsab** [comment]
@cnunciato @ringods  All done

**Review by ringods — APPROVED** [review]

**Review by cnunciato — APPROVED** [review]

**Pull request merged**
