### PR TITLE
community: add ctfer-io/ctfd package

### PR DESCRIPTION
**Pull request by pandatix**
## Description

This PR adds [ctfer-io/pulumi-ctfd](https://github.com/ctfer-io/pulumi-ctfd) to the Pulumi registry.

## Adding a new package?

If this pull request adds a new package:

- [X] The package's schema URL is correct.
- [X] The package metadata file, if present, contains: 
  - [X] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [X] a description that explains what the package does.
  - [X] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [X] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [X] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [X] a brief explanation of what the package is and what it does.
  - [X] at least one representative example in all supported languages.
  - [X] a front-matter property for the `layout` set to `package`.
- [X] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [X] links to SDKs in all supported languages.
  - [X] a copyable command for installing the resource plugin if necessary.
  - [X] an example of configuring the provider with `pulumi config set`.
  - [X] an example of configuring the provider with environment variables.
- [x] A CODEOWNER has reviewed the PR.
- [x] Someone from the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by pandatix** [comment]
up :)

**Comment by ringods** [comment]
@pandatix I created https://github.com/ctfer-io/pulumi-ctfd/pull/33 for you to review and incorporate. Let me know if you have any further questions.

**Comment by pandatix** [comment]
Reviewed and merged :tada:

**Comment by ringods** [comment]
@pandatix please also have a look at the requested package renames:

> Together with the code changes, we would like to indicate that some of the name or namespace for some of the generated SDK packages needs to change. You changed it for your JS/TS package and would like to see the same for your Python and .NET Nuget package. At Pulumi, we like to reserve the package name or prefix pulumi for ourselves.
> 
> Have a look in this section how a community effort documented their naming scheme for all the language SDKs:
https://github.com/pulumiverse/infra/blob/main/README.md#package-registries

https://github.com/ctfer-io/pulumi-ctfd/pull/33#issue-2194494872

**Comment by pandatix** [comment]
> please also have a look at the requested package renames [...]

Oh yes sorry I did not understood it properly in the first time.
I pushed the changes with `v0.1.20`, does it match the expectations now ? :smile:

**Review by ringods — APPROVED** [review]

**Review by sean1588 — APPROVED** [review]

**Pull request merged**
