### PR TITLE
Publish Onboardbase Pulumi to the registry

### PR DESCRIPTION
**Pull request by limistah**

### CODE REVIEW

**Comment by guineveresaenger** [comment]
Hi @limistah - thank you for your pull request.

I see in your `docs/` folder that `_index.md` is empty and would recommend you put an overview description of your package in there (this can mirror your README), as this is the location where our tooling detects your package description.

**Comment by ringods** [comment]
Hello @limistah, next to the remarks @guineveresaenger made, can you also rebase this PR?

**Comment by susanev** [comment]
hi @limistah! we would love to get this package added to the registry, do you need any help getting the docs added to your repo?

**Comment by susanev** [comment]
closing this out for now, pls reach out if we can help in the future!

**Pull request closed without merging**
