### PR TITLE
Update registry browse page for a more compact layout

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
Theme PR: https://github.com/pulumi/theme/pull/384/

This PR adjusts the registry browse page for a more compact view, as we have more providers.  See screenshots + gifs below, as well as behavior live in the generated preview link.

Fixes https://github.com/pulumi/registry/issues/1521

### Individual cards
Screen Shot 2022-11-28 at 12 27 05 PM
Screen Shot 2022-11-28 at 12 27 11 PM

### Cards on hover
Screen Shot 2022-11-28 at 12 34 26 PM
Screen Shot 2022-11-28 at 12 34 34 PM

### Responsive behavior (took these gifs before I slightly decreased the spacing between cards, see below screenshot for accurate view of that spacing)

https://user-images.githubusercontent.com/25756367/204381650-df4c3fc2-6a7a-4f94-bff3-7b225b50383d.mp4

https://user-images.githubusercontent.com/25756367/204381655-b0740faa-da71-4963-8546-bb289a6b098d.mp4

https://user-images.githubusercontent.com/25756367/204381657-cf2e8b79-e0a4-4eda-b7e6-d4c1d6a20ba9.mp4

https://user-images.githubusercontent.com/25756367/204381662-4c0564b5-66e5-4127-ae8a-5810a164db5e.mp4

https://user-images.githubusercontent.com/25756367/204381666-0641ac18-bdad-47a4-8c6a-b791ba14e1a9.mp4

### Multi-cards view, with accurate spacing to what's on the preview link
Screen Shot 2022-11-28 at 12 34 08 PM

### CODE REVIEW

**Comment by susanev** [comment]
@anita-trimbur @kimberleyamackenzie the shadows on the cards in figma seem so much softer than in the preview, do yall see the difference too? can we fix that if so?

**Comment by anita-trimbur** [comment]
wow thanks for pulling this together kimberley! 

couple notes:
1. could we shrink the padding on the featured cards to 16px? i think we may be able to fit `google cloud classic` on a single line so the other cards don't get so tall.
2. it looks like removing the tags impacts the style of the filter chip when it's selected. i think we'll still want that chip in a container. i can play around with how that looks.
Screen Shot 2022-11-28 at 4 53 48 PM

**Comment by kimberleyamackenzie** [comment]
@anita-trimbur cool, i will:

- [ ] Fix up the shadows
- [ ] Adjust the padding

I also noticed the chip thing and fixed it in my theme PR, but the changes didn't get picked up here - will make sure they are when I push a change for the above.  I'm in the middle of another changeset right now, so might not make that change until my EOD/your tomorrow morning.

**Comment by kimberleyamackenzie** [comment]
@anita-trimbur @susanev everything should be fixed up in latest link

**Comment by susanev** [comment]
@anita-trimbur i think we could prolly reduce the amount of space between the featured packages and the filters, but will let you make that decision.

**Review by sean1588 — APPROVED** [review]
this all looks great kimberley! :heart_eyes:  

I also approved the theme PR.

**Comment by anita-trimbur** [comment]
good call @susanev, that spacing should be smaller, probably the same as the gap between the filters and the `a-z packages`, which i think is 32px.

**Comment by kimberleyamackenzie** [comment]
@anita-trimbur here's that updated spacing
Screen Shot 2022-11-29 at 2 30 51 PM

**Review by anita-trimbur — APPROVED** [review]
this lgtm!! <3

**Pull request merged**
