### PR TITLE
Add aci provider to community packages list

### PR DESCRIPTION
**Pull request by danischm**

### CODE REVIEW

**Review by AaronFriel — COMMENTED** [review]
@danischm do you think it would help if your index.md described what ACI is? My first thought was another cloud's "Container Instances" product, but it looks like this is Cisco ACI, a networking solution.

It'll be helpful for users of the provider, our registry, & Pulumi AI if we could add a link and description of what Cisco ACI is. This will also help with users finding this provider and not confusing it with another provider's container instances.

**Comment by danischm** [comment]
It's more than a valid point. :-) I have added a section describing what Cisco ACI is and links.

**Review by AaronFriel — APPROVED** [review]

**Comment by danischm** [comment]
Is there anything else I need to do to get it published? Do I need to publish a new release?

**Comment by AaronFriel** [comment]
Ah, I think I see - the docs at v0.0.4 don't include your changes? To update your docs you should tag a new release and we'll pick that up.

**Pull request merged**
