### PR TITLE
SGA-9575 Adding SatoriCyber Pulumi provider

### PR DESCRIPTION
**Pull request by ron-ts**
## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by ron-ts** [comment]
Hey @sean1588 

Comments fixed 😃 
you can check it out [here](https://github.com/SatoriCyber/pulumi-satori/pull/5)

**Comment by sean1588** [comment]
The provider binaries need to be included in the release artifacts. I chatted with @ron-ts about this in community slack.

**Comment by ringods** [comment]
@ron-ts when will you make a new release including the plugin binaries in the Github Release?

**Comment by ringods** [comment]
@ron-ts checking in again. The last thing missing is a Github Release containing the provider binaries. Any idea when these will/can be released?

**Comment by mjeffryes** [comment]
Closing as abandoned since we haven't heard back since July. Feel free to reopen when you're ready!

**Pull request closed without merging**
