### PR TITLE
add pulumi-prodvana community package

### PR DESCRIPTION
**Pull request by betamike**

### CODE REVIEW

**Review by ringods — COMMENTED** [review]
Hello @betamike, each package in the Pulumi Registry has an `Overview` page and an `Installation & Configuration` page. Here is an example from the `Unifi` provider:

* https://www.pulumi.com/registry/packages/unifi/
* https://www.pulumi.com/registry/packages/unifi/installation-configuration/

These pages are hand-written Markdown files which need to be in the `docs` folder of the Git repository. See here for the same provider:

https://github.com/pulumiverse/pulumi-unifi/tree/main/docs

Before we can add the `prodvana` package to the registry, can you add these two files to your repository and create a new release so these files are tagged appropriately?

**Comment by betamike** [comment]
Oh yes, will do!

**Comment by betamike** [comment]
Ok @ringods I updated and added the [docs](https://github.com/prodvana/pulumi-prodvana/tree/main/docs) directory, and pushed out v0.1.10 including this change.

**Review by cnunciato — COMMENTED** [review]
@betamike Thanks for submitting and congrats on the new provider! I've had a chance to kick the tires a bit, and I'm seeing a few things we should probably fix up before merging.

One is that according to the docs, I should be able to set an `org_slug` and `api_token` with `pulumi config set`:

```
pulumi config set prodvana:org_slug some-value
pulumi config set prodvana:api_token some-value --secret
```

... but when I do this and then preview, I get errors:

```
Diagnostics:
  prodvana:index:Application (my-app):
    error: [AttributeName("org_slug")] Missing Prodvana Org Slug
    error: [AttributeName("api_token")] Missing Prodvana API Token
```

Setting these values as environment variables does seem to work, though. 

From the schema, it looks like they're actually defined as `orgSlug` and `apiToken`:

https://github.com/prodvana/pulumi-prodvana/blob/21649fe5f2ac25be6a97346e5d94ea1d76205f03/provider/cmd/pulumi-resource-prodvana/schema.json#L58C7-L80

And indeed when I configure the stack with these names instead, all seems to go well.

I have a handful of other suggestions for your docs, so I'll collect them all into a PR and submit them for your review. If that looks okay, we should be able to tag a new release and then merge this PR.

**Comment by cnunciato** [comment]
Here's that PR now: https://github.com/prodvana/pulumi-prodvana/pull/19

**Comment by betamike** [comment]
Thanks @cnunciato! Looking over the PR now, and will add a logo as well.

**Comment by betamike** [comment]
@cnunciato I just kicked off a release of a new version (v0.1.11) for pulumi-prodvana to pick up the docs changes. https://github.com/prodvana/pulumi-prodvana/actions/runs/5729130491

**Comment by betamike** [comment]
Hit a small issue after building, fixed and pushing v0.1.12

**Review by cnunciato — APPROVED** [review]
Looks good! I think we're good to merge.

**Comment by betamike** [comment]
Great! @cnunciato how often does is the registry deployed?

**Comment by cnunciato** [comment]
@betamike We have an automated job that checks for new community packages once a day, but we can run that job manually as well. I went ahead and did that a bit ago, so I expect we'll see a PR for the Prodvana provider shortly!

**Pull request merged**
