### PR TITLE
Add DataStax Astra package

### PR DESCRIPTION
**Pull request by vavsab**

### CODE REVIEW

**Comment by stack72** [comment]
Hi @vavsab 

Thanks for the PR here - unfortunately, there are no docs to go with the Provider - in the authoring guide, we suggest the 2 docs pages that we need for the package to be listed

https://www.pulumi.com/docs/guides/pulumi-packages/how-to-author/#write-documentation

You can see how this was done in the scaleway provider - https://github.com/jaxxstorm/pulumi-scaleway/tree/master/docs

Please let me know if you need anything

Paul

**Comment by stack72** [comment]
@vavsab thank you so much for working on that so fast :) I really appreciate it!

**Review by stack72 — APPROVED** [review]

**Comment by vavsab** [comment]
@stack72 Thanks for merging ;). How long does it take to get to the registry https://www.pulumi.com/registry/?
I have a feeling that my change was not enough to make my package visible there.

I see that for scaleway there are a lot of other files like this
https://github.com/pulumi/registry/blob/master/themes/default/data/registry/packages/scaleway.yaml

should I create a PR and generate it?

**Comment by stack72** [comment]
Hey @vavsab 

We have an automated process that pulls these files in :) you did everything you need to! The package build is on its way now - should be published within an hour

Paul

**Pull request merged**
