### PR TITLE
feat: add Pulumi Aquasec provider to Pulumi Registry

### PR DESCRIPTION
**Pull request by dirien**
Hi,

Thi PR adds the Pulumiverse Pulumi Aquasec provider to the Pulumi Registry.

FYI @ringods

### CODE REVIEW

**Comment by dirien** [comment]
Waiting to merge, for the release of the provider https://github.com/pulumiverse/pulumi-aquasec

**Comment by dirien** [comment]
Hi @ringods, this should be fine to merge. The release of the aquasec provider went through

**Comment by ringods** [comment]
@dirien could you rebase this PR?

**Comment by dirien** [comment]
@ringods done 😄

**Review by ringods — APPROVED** [review]

**Pull request merged**
