### PR TITLE
feat: add aquasec and exoscale docs to registry UI.

### PR DESCRIPTION
**Pull request by dirien**
Hi,

This PR is related to following previous PRs #1553 and #1546 to get both provider displayed in the Registry UI.

### CODE REVIEW

**Comment by susanev** [comment]
@dirien heres a pr for the logos https://github.com/pulumi/pulumi-hugo/pull/2176

**Comment by dirien** [comment]
@susanev thanks a lot!

**Comment by ringods** [comment]
@dirien there should not be a need to add these docs manually to this repo. For TF-bridged providers, these should be copied over from the `docs` folder in your repository every time a new release is detected. Are you doing this because of a specific problem?

**Comment by susanev** [comment]
@ringods i think this is the first time these are being added, i don't think they are showing up in the registry at all right now

**Comment by ringods** [comment]
@susanev it isn't needed, even for the first time. See #1605 and #1605 for the process in action.

**Comment by dirien** [comment]
Hi @ringods,

I don't see them in the registry! So I thought I need to create the PR and add them manually.

**Comment by ringods** [comment]
@dirien please copy the logos to your provider repositories.

**Comment by dirien** [comment]
> @dirien please copy the logos to your provider repositories.

In a special folder?

**Comment by susanev** [comment]
@dirien @ringods you do not need to add logos to the repos. if the logo url is set to "" we will pull them from hugo.

**Comment by susanev** [comment]
@ringods to clarify its not that the logos are missing from the registry, the entire packages are not in the registry.

**Comment by dirien** [comment]
So @susanev, i need to set 

```go
	// You may host a logo on a domain you control or add an SVG logo for your package
// in your repository and use the raw content URL for that file as your logo URL.
       LogoURL: "https://avatars3.githubusercontent.com/aquasecurity",
// PluginDownloadURL is an optional URL used to download the Provider
```

To empty?

**Comment by ringods** [comment]
@susanev I know. #1605 and #1606 is the first time the automated publishing process picks up a new release for these providers. Once the automated process merges these, they will become visible shortly after that.

**Comment by susanev** [comment]
@dirien oh sure you can, or you can use what you have? either way someone is going to need the prs that @ringods linked in order for the packages to show up in the registry.

**Comment by dirien** [comment]
Ok, sorry @ringods and @susanev to create any confusion!

**Comment by susanev** [comment]
>Once the automated process merges these

there is not automating merging for community prs, someone needs to manually merge them. i believe those have been sitting for a bit.

**Comment by ringods** [comment]
@susanev @dirien all PRs in this repo starting with `Publish Package Metadata <packagename>@<version>` are merged automatically once day as far as I know.

**Comment by susanev** [comment]
@ringods thats only for pulumi packages, it was turned off for community packages a while ago because they were breaking the builds and needed manual review.

**Comment by ringods** [comment]
@susanev Thanks for letting me know. I wasn't aware of the difference between community & Pulumi packages. 

Let me merge these PRs then.

**Comment by ringods** [comment]
@susanev @dirien FYI the exoscale & aquasec providers are visible in the Registry today!

https://www.pulumi.com/registry/packages/aquasec/
https://www.pulumi.com/registry/packages/exoscale/

**Pull request closed without merging**
