### PR TITLE
Add search in registry browse page

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
Theme PR: https://github.com/pulumi/theme/pull/385

Update registry browse to include a search component.  This search should do the following:

- [ ] Respect other filters added with the tags
- [ ] The tag filters should also respect any content in the search input
- [ ] Clearing results or updating search input terms should update results as expected
- [ ] Tags should now appear under the filters, not next to them
- [ ] Searching "aws" or "amazon" should show results for both, the same for "gcp" and "google cloud"
- [ ] Responsive behavior as expected

https://user-images.githubusercontent.com/25756367/204659863-1540c500-d8fe-47e3-94ad-54d2942b6979.mp4

https://user-images.githubusercontent.com/25756367/204659872-f4e5e4e3-2603-4bec-a1e5-1ff668046080.mp4

https://user-images.githubusercontent.com/25756367/204659884-7c43f00c-387c-48a6-8218-770e32818bab.mp4

Screen Shot 2022-11-29 at 2 10 02 PM
Screen Shot 2022-11-29 at 2 10 10 PM
Screen Shot 2022-11-29 at 2 10 17 PM
Screen Shot 2022-11-29 at 2 10 44 PM

### CODE REVIEW

**Comment by susanev** [comment]
@kimberleyamackenzie i think @anita-trimbur has a more descriptive label for the filter, that id prefer to use if possible

**Comment by anita-trimbur** [comment]
not exactly sure what's going on with them, but sometimes the "x" on the chips break to the next line and other times they do not.

Screen Shot 2022-11-29 at 12 09 34 PM
Screen Shot 2022-11-29 at 12 10 02 PM

also including a screenshot of how the chips would look underneath the filters instead of beside:

Frame 1085

**Comment by kimberleyamackenzie** [comment]
@anita-trimbur Okay, this should be ready for your review now, check out the latest preview!

**Comment by susanev** [comment]
@anita-trimbur that filter icon is pulling a lot of weight, is there an outline icon we can use instead? or a filter icon with lines instead of something with a fill?

**Comment by kimberleyamackenzie** [comment]
@susanev anita and i chatted about this, not a ton of font awesome options w/ our version + non-pro (but maybe there's a better search term i could use?) - https://fontawesome.com/v5/icons/filter?s=duotone&f=classic

**Comment by susanev** [comment]
@kimberleyamackenzie can you make the gcp one come up for either `google` or `google cloud`? sorry for missing that detail previously.

**Comment by susanev** [comment]
@kimberleyamackenzie could we use an svg of the light icon instead?

**Comment by anita-trimbur** [comment]
@susanev yeah unfortunately fontawesome does not have anything else that really works here. i can get an svg, or we could lighten the fontawesome icon to around gray400 like this: 

Screen Shot 2022-11-29 at 5 47 00 PM

@kimberleyamackenzie could we italicize the placeholder text and change that to gray500?

**Comment by kimberleyamackenzie** [comment]
If we go with the svg, we have to pull hugo into the whole thing because that's where the image assets live, so would love to try a lighter gray on the icon first if y'all are good with it

**Comment by susanev** [comment]
kk, lets go with the lighter icon for now. thx for the context!

**Comment by kimberleyamackenzie** [comment]
@susanev @anita-trimbur those changes should be live in the next preview, some screenshots in the meantime
Screen Shot 2022-11-29 at 3 35 52 PM
Screen Shot 2022-11-29 at 3 35 56 PM
Screen Shot 2022-11-29 at 3 36 02 PM
Screen Shot 2022-11-29 at 3 37 48 PM

**Comment by susanev** [comment]
looks good to me, great work on this!

**Review by anita-trimbur — APPROVED** [review]

**Review by sean1588 — APPROVED** [review]
this looks great to me. theme PR also approved!

:shipit:

**Pull request merged**
