### PR TITLE
feat(commnity): add pulumi-descope to registry

### PR DESCRIPTION
**Pull request by omercnet**
## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL in this PR is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a valid plugin download URL. See [Publish Your Package](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#publish-your-package).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] The repository has:
  - [x] a version tag prefixed with `v` that corresponds with a valid GitHub release and published package SDKs
- [ ] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Review by ringods — CHANGES_REQUESTED** [review]
@omercnet can you also add a short Go and .NET example to `docs/_index.md`?

I also noticed that your latest published version is v0.0.3, but the version of your last Nuget package is still 0.0.2

https://www.nuget.org/packages/Descope.Pulumi.Descope

Did something go wrong while publishing the last release?

**Comment by omercnet** [comment]
already had Go, but added dotnet and yaml - https://github.com/descope/pulumi-descope/pull/46
would that work?

**Comment by ringods** [comment]
@omercnet PR with the additional examples approved. After merging, do indeed create a new release. Our registry publishing process only picks up tagged content.

Please also rebase this PR. Since you opened this PR, another provider was already accepted leading to a merge conflict on this same file.

**Comment by omercnet** [comment]
great, will wait for https://github.com/pulumi/pulumi-package-publisher/pull/42 to merge so I can also publish dotnet - will ping you when ready

thanks!

**Comment by omercnet** [comment]
hi @ringods ready for review!

**Review by ringods — APPROVED** [review]

**Review by sean1588 — APPROVED** [review]
thanks @omercnet and @ringods for reviewing. This all looks good to me. Going to ship it and get it published!

**Pull request merged**
