### PR TITLE
feat: add pulumiverse/pulumi-fortios provider

### PR DESCRIPTION
**Pull request by tmeckel**
## Description

Add `pulumiverse/pulumi-fortios` to community-packages/package-list.json

## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] A CODEOWNER has reviewed the PR.
- [x] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Review by ringods — CHANGES_REQUESTED** [review]
@tmeckel I reviewed the provider. Can you have a look at the two items I didn't check:

* at least one representative code example in `docs/_index.md`. Can you add one?
* a copyable command for installing the resource plugin: the command is there but not complete. It is missing the `--server` to point to Pulumiverse (aka the `PluginDownloadURL`.

**Comment by tmeckel** [comment]
@ringods can you please have a look at the PR in the provider repo (https://github.com/pulumiverse/pulumi-fortios/pull/7), if the changes to the documentation reflects your expectations.

**Review by ringods — APPROVED** [review]

**Comment by ringods** [comment]
@tmeckel can you rebase your PR? Due to other merges, there are conflicts now on this package list file.

**Comment by tmeckel** [comment]
> @tmeckel can you rebase your PR? Due to other merges, there are conflicts now on this package list file.

@ringods done 😄

**Comment by cnunciato** [comment]
@tmeckel When I attempt to build the docs, I get an error:

```
panic: fatal: An assertion has failed: duplicate file: router/bgp/_index.md
```

Any ideas?

**Review by cnunciato — APPROVED** [review]
@tmeckel It looks like the docs still contain some HCL. Can you run through these and make sure they're all correct?

image

**Review by cnunciato — CHANGES_REQUESTED** [review]
Sorry, clicked the Approve option by mistake.

**Comment by tmeckel** [comment]
> Sorry, clicked the Approve option by mistake. (See my previous comment.)
@cnunciato Too bad 😁 

Anyways ... I'll update the docs and remove (translate) or remove the HCL code you mentioned in https://github.com/pulumi/registry/pull/4184#pullrequestreview-1977668756

**Comment by t0yv0** [comment]
LMK if I'm needed here. Happy to jump on a call.

**Comment by cnunciato** [comment]
@tmeckel I'm still seeing issues -- left you some comments on the PR. Here's what I see when I render these out:

image

**Comment by tmeckel** [comment]
@cnunciato It is no excuse not to work carefully, but the fact that you have to squeeze the documentation into two files with the community providers makes it easy to lose track in huge files.  

We already had a discussion about this 
https://github.com/pulumi/registry/issues/3159 unfortunately we did not come to a conclusion.

**Review by cnunciato — APPROVED** [review]

**Comment by cnunciato** [comment]
Thanks for rolling with the revisions, @tmeckel!

**Comment by tmeckel** [comment]
@cnunciato created a new PR containing the fixes to the docs
image

**Pull request merged**
