### PR TITLE
Add Koyeb provider to package list

### PR DESCRIPTION
**Pull request by edouardb**
Hi there 👋 

I'm opening a PR for adding the Koyeb Pulumi provider.

Thanks!

### CODE REVIEW

**Comment by ringods** [comment]
Hello @edouardb, may I ask to create a new release which contains your `docs` folder in the git tag? Version [0.1.6](https://github.com/koyeb/pulumi-koyeb/tree/v0.1.6) on your Git repo doesn't contain this yet.

**Comment by edouardb** [comment]
Should be [fixed](https://github.com/koyeb/pulumi-koyeb/tree/v0.1.7)

**Comment by ringods** [comment]
@edouardb thanks for the swift response. The PR is merged, but there are a few more steps on our side to have this become available in the registry itself. Give it a day, 2 max.

**Comment by edouardb** [comment]
Awesome! Thanks @ringods.

**Pull request merged**
