### PR TITLE
Update styles for registry navigation

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
Fixes: https://github.com/pulumi/registry/issues/1704

Update the styles on Registry package page navigation.

Screen Shot 2022-11-30 at 10 23 02 AM
Screen Shot 2022-11-30 at 10 23 09 AM
Screen Shot 2022-11-30 at 10 23 16 AM

### Responsive behavior
Screen Shot 2022-11-30 at 10 49 38 AM
Screen Shot 2022-11-30 at 10 50 22 AM
Screen Shot 2022-11-30 at 10 50 45 AM
Screen Shot 2022-11-30 at 10 50 51 AM

### CODE REVIEW

**Comment by anita-trimbur** [comment]
maybe i'm just hyper fixated on this, but does the change from medium to bold on selection make the page look jumpy? would it look more fluid if we keep the font weight medium even for the selected tabs?

**Comment by kimberleyamackenzie** [comment]
@anita-trimbur personally i think the page looks jumpy even on prod, regardless of the bold change - if you give it a look there, what do you think?

**Comment by anita-trimbur** [comment]
huh i guess it does do that already, doesn't it? yeah you're right, let's leave it as is!

**Review by anita-trimbur — APPROVED** [review]

**Comment by susanev** [comment]
@anita-trimbur ive been meaning to ask you or @jonelleb to add not using font-weight to indicate state change to the design decisions doc because we have ran into this a few times before and it always causes issues. id drop the weight change from this, even if there are other issues on the page.

**Comment by kimberleyamackenzie** [comment]
@anita-trimbur Here's that updated behavior:

- [ ] Default text color to gray 800
- [ ] Hover text color is blue 600
- [ ] No switch to bold for selected tabs


https://user-images.githubusercontent.com/25756367/205183887-1e2034b3-3380-4b59-a3e3-03e17e1950f1.mp4

**Pull request merged**
