### PR TITLE
Add genesiscloud/pulumi-genesiscloud to community package list

### PR DESCRIPTION
**Pull request by philipkrueck**
## Adding a new package?

If this pull request adds a new package:

- [x] The package's schema URL is correct.
- [x] The package metadata file, if present, contains:
  - [x] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [x] a description that explains what the package does.
  - [x] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [x] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [x] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [x] a brief explanation of what the package is and what it does.
  - [x] at least one representative example in all supported languages.
  - [x] a front-matter property for the `layout` set to `package`.
- [x] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [x] links to SDKs in all supported languages.
  - [x] a copyable command for installing the resource plugin if necessary.
  - [x] an example of configuring the provider with `pulumi config set`.
  - [x] an example of configuring the provider with environment variables.
- [x] A CODEOWNER has reviewed the PR.
- [ ] A member of the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Review by ringods — CHANGES_REQUESTED** [review]
@philipkrueck I reviewed your provider but have a few things we would like to see updated.

1. I noticed the `sed` commands in the `Makefile` to rename the packages from the standard Pulumi name(space) to the GenesisCloud ones. There is a standard way to immediately generate packages with the correct names. The Pulumiverse community has it documented on what is needed in `provider/resources.go` to make this happen:
https://github.com/pulumiverse/infra/blob/main/README.md#package-registries

2. We want equal support for all programming languages. Please reactivate the dotnet SDK code generation and update the documentation and code samples.

3. The layout in both the Markdown files in `docs` should be set to `layout: package`.
https://github.com/genesiscloud/pulumi-genesiscloud/blob/93e6300334c99c8a56d15e57a0fbef0a2c7bc18a/docs/installation_configuration.md#L4

4. Please add the copyable command to install the plugin to `docs/installation-configuration.md`. See here for an example: https://github.com/pulumiverse/pulumi-talos/blob/main/docs/installation-configuration.md?plain=1#L16-L24

5. I noticed in your Terraform provider that the `token` can also be specified via an environment variable. This is currently not available in your Pulumi provider. Please update the `Config` block in `provider/resources.go` for this to work. See here for an example: https://github.com/pulumiverse/pulumi-scaleway/blob/2506fe8193caabb54d9c281786f8ef00d93f9c1d/provider/resources.go#L94-L120

6. When the previous step is implemented, please update the docs to explain both ways of configuring the token. See here for an example showing environment variables and stack config options: https://github.com/pulumiverse/pulumi-scaleway/blob/main/docs/installation-configuration.md?plain=1#L42-L89

If you have any further questions around these requests, do not hesitate to ask. We will help you in making your Pulumi provider deliver a top notch experience for your users.

**Comment by ringods** [comment]
@philipkrueck, I was checking the provider code. Thank you for already processing a number of my requests above.

Looking a the docs, I saw a mismatch between the `PluginDownloadURL` configured here (which is good):

https://github.com/genesiscloud/pulumi-genesiscloud/blob/b20b9d4759261454afd0cb28dc41ed07d244b44d/provider/resources.go#L41

and the value described in the docs:

https://github.com/genesiscloud/pulumi-genesiscloud/blob/b20b9d4759261454afd0cb28dc41ed07d244b44d/docs/installation_configuration.md#L21

Can you update the value in the docs with the value from `provider/resources.go`?

**Comment by philipkrueck** [comment]
@ringods Thank you very much for your review

I hope to have addressed all requests:
1. removed the `sed` command from the `Makefile` and updated the `provider/resources.go` accordingly for the node SDK.
2. added support for dotnet: https://www.nuget.org/packages/GenesisCloud.PulumiPackage.Genesiscloud. I updated the `README.md`, `docs/_index.md` and `docs/installation_configuration.md` accordingly.
3. set the `layout: package` in `docs/_index.md` and `docs/installation_configuration.md`.
4. added the copyable command to install the plugin in `docs/installation-configuration.md` and made sure the URL matches in `provider/resources.go`.
5. added the `token` variable to be specified via an env var in `provider/resources.go`.
6. updated the docs accordingly given step 5 in `docs/installation-configuration.md` & `README.md`.

Please let me if you have any further requests and I will get back to you as soon as possible.

**Review by ringods — CHANGES_REQUESTED** [review]
@philipkrueck the build target `build_sdks` has `build_dotnet` still commented out, which results in the .NET SDK not being regenerated with the latest setup from `provider/resources.go`.

Can you update build target in `Makefile`, re-run `make build_sdks`, commit all changed files and create a new release?

**Review by ringods — CHANGES_REQUESTED** [review]
@philipkrueck when running `make build_sdks`, I still get a change for `provider/cmd/pulumi-resource-genesiscloud/schema.json`. The committed file still points to v0.0.18, while my change local file has v0.0.19.

https://github.com/genesiscloud/pulumi-genesiscloud/blob/67dd2ae5ae3ed1e026778967b4f2b74a12d84043/provider/cmd/pulumi-resource-genesiscloud/schema.json

The Pulumi `schema.json` should always be in sync.

**Review by ringods — APPROVED** [review]

**Review by ringods — APPROVED** [review]

**Comment by philipkrueck** [comment]
@ringods Thank you very much for your support!

**Review by sean1588 — APPROVED** [review]

**Pull request merged**
