### PR TITLE
Add caching to some partials

### PR DESCRIPTION
**Pull request by mjeffryes**
Noticed some easy caching wins in the metrics while I was exploring. Not enough of a difference to alter the basic conclusion that we need to split up the builds to add orders of magnitude more docs, but cuts ~25% off the hugo build time. 

Before 
```
Template Metrics:

       cumulative       average       maximum      cache  percent  cached  total
         duration      duration      duration  potential   cached   count  count  template
       ----------      --------      --------  ---------  -------  ------  -----  --------
  14m48.319195422s   24.543272ms    4.3600685s          0        0       0  36194  registry/api.html
    57.338054489s     777.401µs  200.060959ms         39        0       0  73756  partials/docs/table-of-contents.html
    40.205017735s     545.108µs   117.32325ms         49        0       0  73756  partials/registry/package/package-card.html
    23.656516472s      641.48µs  130.627416ms         52        0       0  36878  partials/registry/package/package-card-top-of-page.html
    22.680332673s     614.876µs   86.516125ms          6        0       0  36886  partials/head.html
    17.731934465s     480.826µs   75.169625ms         70        0       0  36878  partials/registry/package-nav.html
     7.797152043s   11.977192ms  143.179542ms          0        0       0    651  registry/package.html
     7.693232474s     208.607µs      30.125ms         56        0       0  36879  partials/registry/breadcrumb.html
     6.476019847s     175.578µs   84.880541ms        100        0       0  36884  partials/docs-top-nav.html
     4.016655875s  4.016655875s  4.016655875s          0        0       0      1  index.json
     3.573024399s      14.707µs   18.013917ms          0        0       0  242935  registry/_markup/render-heading.html
     3.081081994s      83.529µs   82.229584ms         99        0       0  36886  partials/assets.html
     2.325085765s      21.016µs    9.635167ms         55        0       0  110634  partials/registry/package/package-alert.html
     1.690264072s      11.444µs    10.69625ms         86        0       0  147698  partials/registry/package/icon.html
      1.18191975s   1.18191975s   1.18191975s          0        0       0      1  sitemap.xml
       734.8378ms      19.926µs    3.894792ms         33        0       0  36878  partials/registry/left-nav.html
     351.028662ms       9.517µs    2.998542ms        100        0       0  36884  partials/docs/search.html
     312.698916ms   19.543682ms  132.848875ms          0        0       0     16  registry/overview.html
     269.214709ms   15.836159ms  118.619334ms          0        0       0     17  registry/installation.html
     243.384378ms       7.157µs     7.32075ms         92        0       0  34003  partials/registry/package/pulumi-ai.html
     225.389795ms       6.111µs      2.7095ms        100        0       0  36879  partials/docs/footer.html
      197.30218ms       5.349µs       7.108ms        100        0       0  36884  partials/copilot/sidebar.html
      150.26075ms   150.26075ms   150.26075ms          0        0       0      1  registry/list.html
     140.320041ms  140.320041ms  140.320041ms          0        0       0      1  index.html
     139.589875ms   27.917975ms   64.639625ms          0        0       0      5  _default/single.html
      81.902708ms   81.902708ms   81.902708ms          0        0       0      1  404.html
      80.592667ms     857.368µs   34.684917ms          0        0       0     94  _default/_markup/render-table.html
      53.459834ms    8.909972ms   52.974334ms        100        0       0      6  partials/footer.html
      43.709695ms       1.184µs    8.579208ms        100        0       0  36886  partials/top-nav-user-toggle.html
      41.577333ms   41.577333ms   41.577333ms        100        0       0      1  partials/registry/package-list.html
      31.913536ms      17.858µs    1.813542ms          0        0       0   1787  shortcodes/choosable.html
      26.469169ms     145.434µs      1.1515ms         65        0       0    182  partials/registry/package.html
       9.737052ms      26.603µs     794.792µs          0        0       0    366  shortcodes/chooser.html
       9.727294ms     324.243µs    1.283917ms          5        0       0     30  partials/registry/packages/how-to-language-index.html
       7.008585ms      269.56µs    6.683125ms          0        0       0     26  _internal/alias.html
       6.534584ms    3.267292ms    6.213125ms          0        0       0      2  shortcodes/install-pulumi.html
       4.726628ms      73.853µs     1.37625ms          0        0       0     64  shortcodes/notes.html
       4.352291ms    4.352291ms    4.352291ms        100        0       0      1  partials/header.html
       3.426042ms    3.426042ms    3.426042ms          0        0       0      1  _internal/shortcodes/youtube.html
       2.966667ms      95.698µs     401.917µs         25        0       0     31  partials/customer-logo.html
       2.176666ms     725.555µs       1.353ms         33        0       0      3  partials/home/quote.html
       1.835792ms     458.948µs     1.46925ms         67        0       0      4  partials/registry/featured-package.html
       1.744001ms     290.666µs    1.621042ms          0        0       0      6  _internal/shortcodes/relref.html
         935.25µs     467.625µs     934.792µs          0        0       0      2  shortcodes/cli-note.html
          670.5µs      335.25µs     610.625µs         73        0       0      2  partials/icon.html
        627.876µs     313.938µs     627.292µs          0        0       0      2  shortcodes/install-go.html
        515.166µs     128.791µs      388.25µs          0        0       0      4  shortcodes/github-buttons.html
        488.458µs     488.458µs     488.458µs          0        0       0      1  shortcodes/azure-aks-prereqs.html
         470.75µs     235.375µs     470.292µs          0        0       0      2  shortcodes/install-yaml.html
        420.833µs     140.277µs     393.667µs          0        0       0      3  shortcodes/configure-gcp.html
        395.375µs     197.687µs     394.208µs          0        0       0      2  shortcodes/aws-eks-prereqs.html
        320.124µs     106.708µs         296µs        100        0       0      3  partials/customer-logos/snowflake.html
        312.001µs         104µs     303.125µs        100        0       0      3  partials/customer-logos/panther-labs-color.html
        283.917µs     283.917µs     283.917µs        100        0       0      1  partials/customer-logos/starburst.html
        233.001µs      19.416µs     227.208µs          0        0       0     12  shortcodes/aws-resource-note.html
        222.625µs      74.208µs     127.333µs          0        0       0      3  shortcodes/install-python.html
        219.332µs      43.866µs     216.125µs        100        0       0      5  partials/learnmore-contactus.html
        209.833µs      41.966µs     156.292µs          0        0       0      5  shortcodes/cleanup.html
        204.501µs      68.167µs     163.959µs          0        0       0      3  shortcodes/summary.html
        176.125µs     176.125µs     176.125µs          0        0       0      1  _internal/_default/robots.txt
        132.625µs     132.625µs     132.625µs          0        0       0      1  shortcodes/multilang-tutorial-prereqs.html
        130.875µs     130.875µs     130.875µs          0        0       0      1  shortcodes/langfile.html
        122.541µs      40.847µs     121.833µs          0        0       0      3  shortcodes/aws-js-prereqs.html
        121.083µs      40.361µs      118.25µs          0        0       0      3  shortcodes/install-node.html
        120.958µs      40.319µs     119.875µs          0        0       0      3  shortcodes/install-dotnet.html
         79.791µs      39.895µs      78.791µs        100        0       0      2  partials/customer-logos/bmw.html
         77.417µs      38.708µs      76.083µs        100        0       0      2  partials/customer-logos/univision.html
         70.666µs      35.333µs        69.5µs        100        0       0      2  partials/customer-logos/nvidia.html
         70.541µs       35.27µs      69.375µs        100        0       0      2  partials/customer-logos/nubank.html
         66.875µs      33.437µs       65.25µs        100        0       0      2  partials/customer-logos/lemonade.html
         66.666µs      33.333µs      65.625µs        100        0       0      2  partials/customer-logos/docker.html
         64.459µs      32.229µs      63.292µs        100        0       0      2  partials/customer-logos/webflow.html
         60.375µs      30.187µs       59.25µs        100        0       0      2  partials/customer-logos/washington-trust.html
         59.708µs      29.854µs      58.458µs        100        0       0      2  partials/customer-logos/bluenile.html
         58.083µs      29.041µs      57.208µs        100        0       0      2  partials/customer-logos/meta.html
         57.958µs      28.979µs      56.375µs        100        0       0      2  partials/customer-logos/cockroach-labs.html
         57.792µs      28.896µs      56.792µs        100        0       0      2  partials/customer-logos/dutchie.html
         41.917µs      41.917µs      41.917µs        100        0       0      1  partials/icons/hamburger-closed.html
         41.167µs      41.167µs      41.167µs        100        0       0      1  partials/icons/hamburger-open.html
         40.209µs      40.209µs      40.209µs        100        0       0      1  partials/banner.html

INFO  build:  duration 1m55.440029333s
```

After:
```
Template Metrics:

       cumulative       average       maximum      cache  percent  cached  total
         duration      duration      duration  potential   cached   count  count  template
       ----------      --------      --------  ---------  -------  ------  -----  --------
  11m42.488489775s   19.408976ms  3.800724125s          0        0       0  36194  registry/api.html
    40.512899783s     549.282µs   98.703041ms         39        0       0  73756  partials/docs/table-of-contents.html
    27.598959559s     374.192µs     97.6305ms         49        0       0  73756  partials/registry/package/package-card.html
    16.621175322s     450.707µs  102.345125ms         50        0       0  36878  partials/registry/package/package-card-top-of-page.html
    16.574903418s     449.354µs   94.042125ms          6        0       0  36886  partials/head.html
     13.18367903s     357.494µs   94.079458ms         72        0       0  36878  partials/registry/package-nav.html
      6.18625904s     167.744µs   42.188792ms         48        0       0  36879  partials/registry/breadcrumb.html
     5.249539259s    8.063808ms  145.625584ms          0        0       0    651  registry/package.html
     2.742500833s  2.742500833s  2.742500833s          0        0       0      1  index.json
     2.612326056s      10.753µs   10.630958ms          0        0       0  242935  registry/_markup/render-heading.html
     2.356371783s      63.882µs   76.801667ms         99        0       0  36886  partials/assets.html
     1.936153366s        17.5µs   11.116583ms         55        0       0  110634  partials/registry/package/package-alert.html
      896.49225ms   896.49225ms   896.49225ms          0        0       0      1  sitemap.xml
     540.655553ms       14.66µs    2.808208ms         33        0       0  36878  partials/registry/left-nav.html
     378.822047ms       2.564µs    6.269833ms         86      100  147516  147698  partials/registry/package/icon.html
     215.618666ms   13.476166ms  111.744334ms          0        0       0     16  registry/overview.html
     177.555905ms       5.221µs    2.677875ms         92        0       0  34003  partials/registry/package/pulumi-ai.html
     151.337125ms    8.902183ms   94.016917ms          0        0       0     17  registry/installation.html
     149.836292ms   29.967258ms   74.521334ms          0        0       0      5  _default/single.html
        137.826ms     137.826ms     137.826ms          0        0       0      1  index.html
     132.931916ms  132.931916ms  132.931916ms          0        0       0      1  registry/list.html
     105.229882ms    1.119466ms   47.805833ms          0        0       0     94  _default/_markup/render-table.html
      85.345083ms   85.345083ms   85.345083ms          0        0       0      1  404.html
      80.575888ms       2.184µs   11.038916ms        100      100   36883  36884  partials/copilot/sidebar.html
      72.447916ms       1.964µs    8.811875ms        100      100   36883  36883  partials/docs-top-nav
      47.484959ms    7.914159ms   47.466084ms        100       83       5      6  partials/footer.html
      37.431709ms   37.431709ms   37.431709ms        100        0       0      1  partials/registry/package-list.html
      33.688292ms         913ns    1.681583ms        100      100   36883  36884  partials/docs/search.html
      31.886878ms         864ns       531.5µs        100      100   36878  36879  partials/docs/footer.html
      24.557044ms     134.928µs       1.345ms         65        0       0    182  partials/registry/package.html
      22.192854ms      12.419µs    1.499625ms          0        0       0   1787  shortcodes/choosable.html
       7.262166ms     242.072µs     744.917µs          5        0       0     30  partials/registry/packages/how-to-language-index.html
       5.876336ms      16.055µs     536.833µs          0        0       0    366  shortcodes/chooser.html
       4.590837ms     148.091µs    2.193792ms         25        0       0     31  partials/customer-logo.html
       3.491376ms     134.283µs    3.200542ms          0        0       0     26  _internal/alias.html
         2.4235ms      2.4235ms      2.4235ms          0        0       0      1  partials/docs-top-nav.html
       2.212751ms      34.574µs     278.625µs          0        0       0     64  shortcodes/notes.html
        2.19175ms     730.583µs    1.591167ms         33        0       0      3  partials/home/quote.html
        979.583µs     979.583µs     979.583µs          0        0       0      1  _internal/shortcodes/youtube.html
        846.665µs      141.11µs     660.375µs          0        0       0      6  _internal/shortcodes/relref.html
        773.166µs     386.583µs     575.041µs          0        0       0      2  shortcodes/install-pulumi.html
        697.833µs     174.458µs     536.167µs         67        0       0      4  partials/registry/featured-package.html
        397.583µs     397.583µs     397.583µs        100        0       0      1  partials/header.html
        251.833µs      62.958µs     160.083µs          0        0       0      4  shortcodes/github-buttons.html
        206.625µs     103.312µs     206.292µs        100        0       0      2  partials/customer-logos/webflow.html
        196.751µs      98.375µs     194.917µs          0        0       0      2  shortcodes/cli-note.html
        189.126µs      37.825µs     186.167µs        100        0       0      5  partials/learnmore-contactus.html
        175.456µs      35.091µs     122.041µs          0        0       0      5  shortcodes/cleanup.html
        175.375µs      58.458µs      164.75µs          0        0       0      3  shortcodes/configure-gcp.html
        167.833µs      83.916µs     167.458µs          0        0       0      2  shortcodes/aws-eks-prereqs.html
        166.957µs      55.652µs     132.333µs          0        0       0      3  shortcodes/summary.html
        156.916µs     156.916µs     156.916µs          0        0       0      1  shortcodes/azure-aks-prereqs.html
        155.916µs      77.958µs     155.541µs          0        0       0      2  shortcodes/install-go.html
        134.042µs      67.021µs     133.792µs          0        0       0      2  shortcodes/install-yaml.html
        125.125µs     125.125µs     125.125µs          0        0       0      1  shortcodes/multilang-tutorial-prereqs.html
        125.042µs       41.68µs      124.25µs          0        0       0      3  shortcodes/aws-js-prereqs.html
        122.042µs       40.68µs     119.625µs          0        0       0      3  shortcodes/install-python.html
        119.958µs     119.958µs     119.958µs          0        0       0      1  shortcodes/langfile.html
            119µs       9.916µs     113.459µs          0        0       0     12  shortcodes/aws-resource-note.html
        115.417µs      38.472µs     114.542µs          0        0       0      3  shortcodes/install-dotnet.html
        114.958µs      38.319µs     113.125µs          0        0       0      3  shortcodes/install-node.html
        107.791µs       35.93µs     103.625µs        100        0       0      3  partials/customer-logos/snowflake.html
        100.583µs      50.291µs      63.333µs         73        0       0      2  partials/icon.html
          90.75µs       30.25µs       85.25µs        100        0       0      3  partials/customer-logos/panther-labs-color.html
         84.167µs      84.167µs      84.167µs        100        0       0      1  partials/customer-logos/starburst.html
             73µs        36.5µs      72.667µs        100        0       0      2  partials/customer-logos/nvidia.html
         59.208µs      29.604µs          59µs        100        0       0      2  partials/customer-logos/univision.html
         59.041µs       29.52µs      58.833µs        100        0       0      2  partials/customer-logos/docker.html
          58.75µs      29.375µs        58.5µs        100        0       0      2  partials/customer-logos/nubank.html
          58.25µs      29.125µs      58.083µs        100        0       0      2  partials/customer-logos/washington-trust.html
         56.291µs      28.145µs      56.125µs        100        0       0      2  partials/customer-logos/dutchie.html
         55.624µs      27.812µs      55.333µs        100        0       0      2  partials/customer-logos/bluenile.html
         51.958µs      25.979µs      51.791µs        100        0       0      2  partials/customer-logos/cockroach-labs.html
         51.542µs      25.771µs      50.875µs        100        0       0      2  partials/customer-logos/lemonade.html
         46.459µs      23.229µs      46.167µs        100        0       0      2  partials/customer-logos/meta.html
         40.793µs      20.396µs      40.584µs        100        0       0      2  partials/customer-logos/bmw.html
         29.375µs      29.375µs      29.375µs        100        0       0      1  partials/icons/hamburger-closed.html
          27.75µs       27.75µs       27.75µs        100        0       0      1  partials/banner.html
             27µs          27µs          27µs        100        0       0      1  partials/icons/hamburger-open.html
         25.791µs       8.597µs      25.417µs        100        0       0      3  partials/top-nav-user-toggle.html
         16.416µs      16.416µs      16.416µs          0        0       0      1  _internal/_default/robots.txt

INFO  build:  duration 1m31.82220125s
```

### CODE REVIEW

**Comment by mjeffryes** [comment]
Hmmm... This may not be worth it after all. I don't see the same delta in CI (Possibly it's because the build on ci is memory bound already?

**Comment by iwahbe** [comment]
> Hmmm... This may not be worth it after all. I don't see the same delta in CI (Possibly it's because the build on ci is memory bound already?

I'm afraid that caching more is as-slow or slower then the prior state (a fresh CI run for a separate test took 30m for the "Pull request / Build and deploy preview (pull_request)" step.

I think that the performance bottleneck is memory, and using more memory (by caching) has us using swap or inefficiently aggressive GC.

**Comment by mjeffryes** [comment]
FWIW, I did notice that we're setting `GOGC=3` in the ci build scripts. I think setting `GOMEMLIMIT` or `HUGO_MEMORYLIMIT` instead would let use use more of the memory on the box without OOM'ing. (I tested locally with the later, not sure if the former is more general)

**Comment by iwahbe** [comment]
Honestly, we might be able to get away with removing the limit entirely: https://github.com/pulumi/registry/pull/5920.

**Comment by iwahbe** [comment]
I have rebased on top of `master` with #5920 merged. I'm hoping we will see a performance win there.

**Comment by iwahbe** [comment]
It might be worth opening another PR to confirm, but this looks like a large performance degradation: new builds (post #5920) take 20 minutes, this takes 28m.

**Comment by mjeffryes** [comment]
I don't see evidence that (post https://github.com/pulumi/registry/pull/5920) builds are down to 20m. (And that would we very surprising given that the hugo build was only ~3min before that change anyway.) I think the reduction to 20m you saw was from parallelizing resourcedocsgen? 

I do agree that there doesn't seem to be any speed up in CI though, so lets just drop this change for now. I'm not sure why the caching doesn't have any effect in CI, but we can always try looking into this again later if hugo build time becoomes more dominant.

**Pull request closed without merging**
