### PR TITLE
Updating Twingate Python and TS example

### PR DESCRIPTION
**Pull request by chenbishop**

### CODE REVIEW

**Comment by ringods** [comment]
@chenbishop There is no need to update these files in this repo manually. I checked and noticed your package isn't automatically updated by our publishing process.

Can you send us a PR adding the details of your provider repository to this list? `repoSlug` is the part after `https://github.com/` of your Github repo.

https://github.com/pulumi/registry/blob/master/community-packages/package-list.json

Once it is added to this list, we will check regularly for new releases of your package in the Github repo.

If you copy the files from this repo:

https://github.com/pulumi/registry/tree/master/themes/default/content/registry/packages/twingate

back to the top-level `docs` folder in your own repo, we will copy over these files from your repo at every release. ([Example from another provider](https://github.com/pulumiverse/pulumi-unifi/tree/main/docs))

**Comment by chenbishop** [comment]
@ringods Thank you very much for your help. 

I have:
1. Created a new pull request to add twingate pulumi provider https://github.com/pulumi/registry/pull/2114 in the list
2. Created docs structure and content in the twingate pulumi repo https://github.com/Twingate-Labs/pulumi-twingate/tree/master/docs

**Comment by ringods** [comment]
@chenbishop before I merge the other PR, can you first create a release in your repo that contains the new `docs` folder? Then we are all set.

**Comment by chenbishop** [comment]
@ringods thank you very much! the new version v0.0.35 is now released.

**Comment by ringods** [comment]
This open PR is detected in the package update step. Closing this PR to prevent the run to halt prematurely.

https://github.com/pulumi/registry/actions/runs/4290298828/jobs/7474181754

**Comment by ringods** [comment]
@chenbishop we are almost there. By closing this PR, the update check correctly detects there is a newer version, but the processing fails because you have a capital in the category name here:

https://github.com/Twingate-Labs/pulumi-twingate/blob/73cc978a3468911db7c74e020bca56b318dec2ca/provider/resources.go#L62

Failure: https://github.com/pulumi/registry/actions/runs/4290407995/jobs/7474403991

Can you update `category/Infrastructure` to `category/infrastructure`, rebuild everything so the lowercase version ends up in `schema.json`, followed by creating (yet) another release?

**Comment by chenbishop** [comment]
@ringods Thank you very much for the help. I have made the change, rebuilt and re-released.

**Pull request closed without merging**
