### PR TITLE
Revert "Fix edit links"

### PR DESCRIPTION
**Pull request by susanev**
Reverts pulumi/registry#800

### CODE REVIEW

**Review by cnunciato — APPROVED** [review]

**Comment by cnunciato** [comment]
@susanev Is there a follow-up issue to address the 404s now happening on the how-to guides? Just want to make sure we have a plan to close the loop here.

**Comment by susanev** [comment]
@cnunciato oh i think i misunderstood your comment before. i thought you preferred this one over removing the links until we can fix them. i can bring the how-to guides over on monday, but prolly wont have time to do it before then.

**Comment by cnunciato** [comment]
> i thought you preferred this one over removing the links until we can fix them.

Yep, I do, all good -- I was just wondering whether we have an issue to track finishing things off.

**Comment by susanev** [comment]
ah, i left this open. will add more context there in a bit.
https://github.com/pulumi/registry/issues/834

**Pull request merged**
