### PR TITLE
Test customized docsgen

### PR DESCRIPTION
**Pull request by t0yv0**
## Adding a new package?

If this pull request adds a new package:

- [ ] The package's schema URL is correct.
- [ ] The package metadata file, if present, contains: 
  - [ ] a supported category (one of `Cloud`, `Infrastructure`, `Network`, `Database`, `Monitoring`, or `Utility`).
  - [ ] a description that explains what the package does.
  - [ ] a valid logo URL that points to a PNG whose dimensions conform to the others in this repo (e.g., 100x100).
  - [ ] a version number prefixed with `v` that corresponds with a valid GitHub release.
- [ ] The package repo contains an Overview doc (`/docs/_index.md`) that includes:
  - [ ] a brief explanation of what the package is and what it does.
  - [ ] at least one representative example in all supported languages.
  - [ ] a front-matter property for the `layout` set to `package`.
- [ ] The package repo contains an Installation and Configuration doc (`/docs/installation-configuration.md`) that includes:
  - [ ] links to SDKs in all supported languages.
  - [ ] a copyable command for installing the resource plugin if necessary.
  - [ ] an example of configuring the provider with `pulumi config set`.
  - [ ] an example of configuring the provider with environment variables.
- [ ] Someone from the @pulumi/ai team has reviewed the PR.
- [ ] Someone from the @pulumi/docs team has reviewed all documentation.

### CODE REVIEW

**Comment by t0yv0** [comment]
Looks like registry needs to be on Go 1.20.x

https://pkg.go.dev/strings#CutPrefix missing

**Comment by t0yv0** [comment]
Looks like something in AWS metadata is in violation of a recently introduced check https://github.com/pulumi/pulumi/pull/14637/

**Comment by t0yv0** [comment]
Actually that was https://github.com/pulumi/pulumi-aws-iam/pull/19

**Comment by cnunciato** [comment]
>Looks like registry needs to be on Go 1.20.x

@t0yv0 Sorry about that -- this should fix that up: https://github.com/pulumi/registry/pull/3730

**Comment by iwahbe** [comment]
@t0yv0 Are you done with this test?

**Pull request closed without merging**
