### PR TITLE
Added Port as a community package to registry

### PR DESCRIPTION
**Pull request by danielsinai**

### CODE REVIEW

**Review by dirien — APPROVED** [review]
LGTM!

**Comment by susanev** [comment]
hi folks! this needs docs, before we can merge this into registry.
https://www.pulumi.com/docs/guides/pulumi-packages/how-to-author/

**Comment by susanev** [comment]
good call @ringods i hadnt looked at that yet, that will need to change as well.

**Comment by danielsinai** [comment]
I will handle it and update the PR soon, thanks 😄 
BTW, why is the requirement of the repo name to end with the `port` suffix?

**Comment by ringods** [comment]
@danielsinai once your repo is registered, we have code in a few places, one of which is in Github Actions, which does pattern matching on the name of the repo to check for new releases of your provider. We are not in a situation at the moment that we can drop that requirement.

**Comment by dirien** [comment]
@danielsinai: New PR for the new registry of the provider with correct repo name `pulumi-port` 


https://github.com/pulumi/registry/pull/2814

**Pull request closed without merging**
